language: c
sudo: false

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended

env:
  - R_LIBS_USER=~/R/library

cache:
  directories:
    $R_LIBS_USER

before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'if (length(find.package("covr", quiet = TRUE)) == 0L) { install.packages("covr", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'library(devtools);update_packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'library(devtools);install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'

script:
  - Rscript -e 'devtools::check()'

after_success:
  - Rscript -e 'covr::codecov()'
